-- Seed all existing content data
INSERT INTO content_entries (id, title, link, tracking_link, platform, publication_date, status, views, content_type, tags, notes, created_at, updated_at) VALUES
-- July 2025 Posts (Week 1)
('1', 'Add Billing to Your SaaS in Under 10 Minutes (With Kinde)', 'https://dev.to/sholajegede/add-billing-to-your-saas-in-under-10-minutes-with-kinde-20md', 'https://dev.to/sholajegede/add-billing-to-your-saas-in-under-10-minutes-with-kinde-20md?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post1', 'Dev.to', '2025-07-17', 'Published', 0, 'Tutorial', '["Kinde", "Billing", "SaaS", "Tutorial"]', 'Week 1 - Post 1', NOW(), NOW()),
('2', 'How Kinde Billing Actually Works', 'https://dev.to/sholajegede/how-kinde-billing-actually-works-8fc', 'https://dev.to/sholajegede/how-kinde-billing-actually-works-8fc?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post2', 'Dev.to', '2025-07-18', 'Published', 0, 'Guide', '["Kinde", "Billing", "Deep Dive"]', 'Week 1 - Post 2', NOW(), NOW()),
('3', 'Part 1: I Wanted to Learn Faster — So I Built a Voice AI Tutor with GPT-4 in a Weekend', 'https://dev.to/sholajegede/i-wanted-to-learn-faster-so-i-built-a-voice-ai-tutor-with-gpt-4-in-a-weekend-3ke0', 'https://dev.to/sholajegede/i-wanted-to-learn-faster-so-i-built-a-voice-ai-tutor-with-gpt-4-in-a-weekend-3ke0?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post3', 'Dev.to', '2025-07-19', 'Published', 0, 'Case Study', '["AI", "Voice", "GPT-4", "Build in Public", "Kinde"]', 'Week 1 - Post 3. LearnFlow AI series Part 1', NOW(), NOW()),
('4', 'Part 2: How I Turned a Voice AI Demo Into a Real SaaS App — Auth, Access, and Limits', 'https://dev.to/sholajegede/how-i-turned-a-voice-ai-demo-into-a-real-saas-app-auth-access-and-limits-14fl', 'https://dev.to/sholajegede/how-i-turned-a-voice-ai-demo-into-a-real-saas-app-auth-access-and-limits-14fl?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post4', 'Dev.to', '2025-07-20', 'Published', 0, 'Case Study', '["AI", "SaaS", "Auth", "Kinde"]', 'Week 1 - Post 4. LearnFlow AI series Part 2', NOW(), NOW()),
('5', 'Part 3: From Side Project to Paid SaaS — Adding Subscriptions & Usage Tiers to an AI App', 'https://dev.to/sholajegede/from-side-project-to-paid-saas-adding-subscriptions-usage-tiers-to-an-ai-app-1ml4', 'https://dev.to/sholajegede/from-side-project-to-paid-saas-adding-subscriptions-usage-tiers-to-an-ai-app-1ml4?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post5', 'Dev.to', '2025-07-21', 'Published', 0, 'Case Study', '["SaaS", "Subscriptions", "Pricing", "Kinde"]', 'Week 1 - Post 5. LearnFlow AI series Part 3', NOW(), NOW()),
-- July 2025 Posts (Week 2)
('6', 'Before Launching My AI Tool, I Rebuilt the Onboarding 3 Times. Here''s Why', 'https://dev.to/sholajegede/before-launching-my-ai-tool-i-rebuilt-the-onboarding-3-times-heres-why-1hm6', 'https://dev.to/sholajegede/before-launching-my-ai-tool-i-rebuilt-the-onboarding-3-times-heres-why-1hm6?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post6', 'Dev.to', '2025-07-24', 'Published', 0, 'Case Study', '["Onboarding", "UX", "AI", "Kinde"]', 'Week 2 - Post 6', NOW(), NOW()),
('7', 'I Built a Voice-First AI App in One Weekend — Here''s Everything I Got Right (and Wrong)', 'https://dev.to/sholajegede/i-built-a-voice-first-ai-app-in-one-weekend-heres-everything-i-got-right-and-wrong-27fa', 'https://dev.to/sholajegede/i-built-a-voice-first-ai-app-in-one-weekend-heres-everything-i-got-right-and-wrong-27fa?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post7', 'Dev.to', '2025-07-25', 'Published', 0, 'Case Study', '["Voice AI", "Lessons Learned", "Build in Public", "Kinde"]', 'Week 2 - Post 7', NOW(), NOW()),
('8', 'What My First 10 Users Taught Me About Pricing, Access, and Product-friction', 'https://dev.to/sholajegede/what-my-first-10-users-taught-me-about-pricing-access-and-product-friction-na1', 'https://dev.to/sholajegede/what-my-first-10-users-taught-me-about-pricing-access-and-product-friction-na1?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post8', 'Dev.to', '2025-07-26', 'Published', 0, 'Case Study', '["User Feedback", "Pricing", "Product", "Kinde"]', 'Week 2 - Post 8', NOW(), NOW()),
('9', '3 Mistakes I Made Shipping My AI MVP Too Fast — and How I Fixed Them', 'https://dev.to/sholajegede/3-mistakes-i-made-shipping-my-ai-mvp-too-fast-and-how-i-fixed-them-300m', 'https://dev.to/sholajegede/3-mistakes-i-made-shipping-my-ai-mvp-too-fast-and-how-i-fixed-them-300m?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post9', 'Dev.to', '2025-07-27', 'Published', 0, 'Case Study', '["MVP", "Mistakes", "AI", "Kinde"]', 'Week 2 - Post 9', NOW(), NOW()),
('10', 'Why Usage-Based Pricing Felt Right for My AI Tool — and How I Pulled It Off', 'https://dev.to/sholajegede/why-usage-based-pricing-felt-right-for-my-ai-tool-and-how-i-pulled-it-of-553n', 'https://dev.to/sholajegede/why-usage-based-pricing-felt-right-for-my-ai-tool-and-how-i-pulled-it-of-553n?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post10', 'Dev.to', '2025-07-28', 'Published', 0, 'Guide', '["Usage-Based Pricing", "AI", "Monetization", "Kinde"]', 'Week 2 - Post 10', NOW(), NOW()),
-- July 2025 Posts (Week 3)
('11', 'What Stripe Got Right About Dev Experience — and What Kinde Is Evolving', 'https://dev.to/sholajegede/what-stripe-got-right-about-dev-experience-and-what-kinde-is-evolving-20p2', 'https://dev.to/sholajegede/what-stripe-got-right-about-dev-experience-and-what-kinde-is-evolving-20p2?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post11', 'Dev.to', '2025-07-31', 'Published', 0, 'Opinion', '["Developer Experience", "Stripe", "Kinde", "Comparison"]', 'Week 3 - Post 11', NOW(), NOW()),
('12', 'Auth and Billing in One API Call: A Pattern Worth Betting On', 'https://dev.to/sholajegede/auth-and-billing-in-one-api-call-a-pattern-worth-betting-on-57jl', 'https://dev.to/sholajegede/auth-and-billing-in-one-api-call-a-pattern-worth-betting-on-57jl?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post12', 'Dev.to', '2025-08-01', 'Published', 0, 'Guide', '["Auth", "Billing", "API Design", "Kinde"]', 'Week 3 - Post 12', NOW(), NOW()),
('13', 'How I Designed a Credit System That Actually Makes Users Upgrade', 'https://dev.to/sholajegede/how-i-designed-a-credit-system-that-actually-makes-users-upgrade-59h5', 'https://dev.to/sholajegede/how-i-designed-a-credit-system-that-actually-makes-users-upgrade-59h5?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post13', 'Dev.to', '2025-08-02', 'Published', 0, 'Case Study', '["Credits", "Monetization", "Growth", "Kinde"]', 'Week 3 - Post 13', NOW(), NOW()),
('14', 'The Unseen Cost of Speed: What I''d change if I rebuilt my AI saas today', 'https://dev.to/sholajegede/the-unseen-cost-of-speed-what-id-change-if-i-rebuilt-my-ai-saas-today-455m', 'https://dev.to/sholajegede/the-unseen-cost-of-speed-what-id-change-if-i-rebuilt-my-ai-saas-today-455m?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post14', 'Dev.to', '2025-08-03', 'Published', 0, 'Opinion', '["Retrospective", "AI", "SaaS", "Kinde"]', 'Week 3 - Post 14', NOW(), NOW()),
('15', 'Why Building with Voice Is a UX Design Challenge, Not Just a Tech One', 'https://dev.to/sholajegede/why-building-with-voice-is-a-ux-design-challenge-not-just-a-tech-one-3lh5', 'https://dev.to/sholajegede/why-building-with-voice-is-a-ux-design-challenge-not-just-a-tech-one-3lh5?utm_source=kinde&utm_medium=devrel&utm_campaign=learnflowai&creative=post15', 'Dev.to', '2025-08-04', 'Published', 0, 'Opinion', '["Voice UX", "Design", "AI", "Kinde"]', 'Week 3 - Post 15', NOW(), NOW()),
-- November 2025 Retainer Posts
('16', 'The Complete Guide to Usage-Based Billing in AI Apps: Tokens, Credits, Overage, and Revenue Recognition Explained', '', '', 'freeCodeCamp', '2025-11-15', 'Published', 0, 'Guide', '["Billing", "AI", "Usage-Based", "Kinde"]', 'November 2025 - freeCodeCamp', NOW(), NOW()),
('17', 'Why Your SaaS Can''t Charge Per-Seat Anymore (And What Replaces It)', '', '', 'Dev.to', '2025-11-20', 'Draft', 0, 'Opinion', '["SaaS", "Pricing", "Kinde"]', 'November 2025 - Dev.to', NOW(), NOW()),
('18', 'AI Generated 47% of My Code Last Month. Here''s What I Actually Had to Fix', '', '', 'Dev.to', '2025-11-25', 'Draft', 0, 'Case Study', '["AI", "Coding", "Kinde"]', 'November 2025 - Dev.to', NOW(), NOW()),
-- December 2025 Retainer Posts
('19', 'How to Build Team Collaboration Features in Your AI App: Invitations, Role Switching, and Cross-Organization Access', '', '', 'freeCodeCamp', '2025-12-10', 'Published', 0, 'Tutorial', '["Teams", "Collaboration", "AI", "Kinde"]', 'December 2025 - freeCodeCamp', NOW(), NOW()),
('20', 'How to Add Team Collaboration to Your v0.app AI Generated App in Under 5 Minutes', '', '', 'Dev.to', '2025-12-15', 'Published', 0, 'Tutorial', '["v0", "Teams", "AI", "Kinde"]', 'December 2025 - Dev.to', NOW(), NOW()),
('21', 'How to Build Passwordless Auth That Doesn''t Frustrate Users (Magic Links, One-Time Codes, and What Actually Works)', '', '', 'Dev.to', '2025-12-20', 'Published', 0, 'Tutorial', '["Auth", "Passwordless", "UX", "Kinde"]', 'December 2025 - Dev.to', NOW(), NOW()),
-- January 2026 Retainer Posts
('22', 'How to Build and Deploy Tetris Inside ChatGPT: A Complete Guide to the Vercel ChatGPT Apps SDK with TypeScript, Convex, and Kinde OAuth', '', '', 'freeCodeCamp', '2026-01-10', 'Draft', 0, 'Tutorial', '["ChatGPT", "Vercel", "Convex", "Kinde"]', 'January 2026 - freeCodeCamp', NOW(), NOW()),
('23', 'How to Build Self-Service Billing: Let Users Upgrade Their Own Plans', '', '', 'Dev.to', '2026-01-15', 'Draft', 0, 'Tutorial', '["Billing", "Self-Service", "Kinde"]', 'January 2026 - Dev.to', NOW(), NOW()),
('24', 'How to Build Organization-Scoped M2M Authentication for Multi-Tenant APIs', '', '', 'Dev.to', '2026-01-20', 'Draft', 0, 'Tutorial', '["M2M", "Auth", "Multi-Tenant", "Kinde"]', 'January 2026 - Dev.to', NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  link = EXCLUDED.link,
  tracking_link = EXCLUDED.tracking_link,
  platform = EXCLUDED.platform,
  publication_date = EXCLUDED.publication_date,
  status = EXCLUDED.status,
  views = EXCLUDED.views,
  content_type = EXCLUDED.content_type,
  tags = EXCLUDED.tags,
  notes = EXCLUDED.notes,
  updated_at = NOW();
